import 'dart:math';

import 'package:flutter_test/flutter_test.dart';
import 'package:ledgr/core/security/encryption_key_service.dart';

class _InMemoryStore implements SecureKeyValueStore {
  final Map<String, String> _data = {};

  @override
  Future<String?> read(String key) async => _data[key];

  @override
  Future<void> write(String key, String value) async => _data[key] = value;

  @override
  Future<void> delete(String key) async => _data.remove(key);
}

void main() {
  group('EncryptionKeyService', () {
    test('generates a 32-byte key on first call', () async {
      final service = EncryptionKeyService(
        storage: _InMemoryStore(),
        random: Random(42),
      );
      final key = await service.getOrCreateKey();
      expect(key.length, 32);
      expect(key.every((b) => b >= 0 && b <= 255), true);
    });

    test('returns the same key on subsequent calls', () async {
      final store = _InMemoryStore();
      final service = EncryptionKeyService(storage: store, random: Random(42));
      final first = await service.getOrCreateKey();
      final second = await service.getOrCreateKey();
      expect(first, second);
    });

    test('persists across service instances (same backing store)', () async {
      final store = _InMemoryStore();
      final firstService =
          EncryptionKeyService(storage: store, random: Random(1));
      final secondService =
          EncryptionKeyService(storage: store, random: Random(2));

      final first = await firstService.getOrCreateKey();
      final second = await secondService.getOrCreateKey();
      expect(
        first,
        second,
        reason: 'New instance must read existing persisted key',
      );
    });

    test('destroyKey forces fresh key on next call', () async {
      final store = _InMemoryStore();
      final service = EncryptionKeyService(storage: store, random: Random(1));

      final original = await service.getOrCreateKey();
      await service.destroyKey();
      final regenerated = await service.getOrCreateKey();

      expect(regenerated.length, 32);
      // With Random(1) reseeded behaviour, but since we keep using same Random
      // instance the regenerated bytes will differ from the original.
      expect(regenerated, isNot(equals(original)));
    });

    test('rejects malformed stored value and regenerates', () async {
      final store = _InMemoryStore();
      await store.write(
        'ledgr.hive.master_key.v1',
        'not-valid-base64-of-32-bytes',
      );
      final service = EncryptionKeyService(storage: store, random: Random(1));
      final key = await service.getOrCreateKey();
      expect(key.length, 32);
    });
  });
}
